# -*- coding: utf-8 -*-
"""Untitled0.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qJdOdk4vNGeNwmIN9eHG04zAo7KEAo9Y
"""

import pandas as pd
cont ='/content/Libro1.xlsx'

datos= pd.read_excel(cont)
datos['E-mail']